name: Build and Release mcpify

on:
  release:
    types: [ created ]
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.platform.os }}-${{ matrix.platform.arch }})
    runs-on: ${{ matrix.platform.runner }}

    strategy:
      matrix:
        platform:
        - os: darwin
          arch: amd64
          runner: macos-13 # Intel runner
        - os: darwin
          arch: arm64
          runner: macos-latest # ARM runner
        - os: linux
          arch: amd64
          runner: ubuntu-latest
        - os: linux
          arch: arm64
          runner: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Install dependencies
      if: matrix.platform.os == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev

    - name: Set up cross-compilation for Linux ARM64
      if: matrix.platform.os == 'linux' && matrix.platform.arch == 'arm64'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

    - name: Build binary
      env:
        GOOS: ${{ matrix.platform.os }}
        GOARCH: ${{ matrix.platform.arch }}
      run: |
        go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -o mcpify-${{ matrix.platform.os }}-${{ matrix.platform.arch }} ./cmd/mcpify

    - name: Make binary executable
      run: chmod +x mcpify-${{ matrix.platform.os }}-${{ matrix.platform.arch }}

    - name: Upload to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: mcpify-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
